name = "api"
main = "src/index.ts"
compatibility_date = "2023-06-15"

account_id = "16f8e12d2a44b13afb75f5f965c9c047"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "sessiongo"
database_id = "e44dae81-093f-49d8-bffd-761e29dd4217"

[[r2_buckets]]
binding = 'STORAGE' # <~ valid JavaScript variable name
bucket_name = 'sessiongo'
preview_bucket_name= 'sessiongo-preview'
