openapi: 3.0.0
info:
  title: SessionGO API
  version: 0.1.0
paths:
  /users:
    $ref: './users.yaml'
  /events:
    $ref: './events.yaml'
  /events/{id}:
    $ref: './events_id.yaml'
  /users/{id}/events:
    $ref: './users_id_events.yaml'
