openapi: 3.0.0
info:
  title: SessionGO API
  version: 0.1.0
paths:
  /users:
    $ref: './paths/users.yml'
  /events:
    $ref: './paths/events.yml'
  /events/{id}:
    $ref: './paths/events_id.yml'
  /users/{id}/events:
    $ref: './paths/users_id_events.yml'
